name: test-cicd
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4.5.0
        with:
          name: prod-files
          path: ./build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          path: ./build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_CD_TEST }}
          publish_dir: ./build/prod-files
